excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kc0tfb.github.io
title: Peter Gamache
tagline: Security is a process, not a product.
description: Linux, IT security, amateur radio and other musings.
paginate: 5
